### ISSUE TITLE
Bulbs unable to join SSID (initial setup) if SSID is hidden

### ISSUE THREAD

**Issue by jonofmac** [KaufHA/kauf-rgbww-bulbs#14]
Hello, Just got my order of 12 bulbs (very excited to give these a go!). While setting them up, I noticed a few things. They're all on older firmware (1.72 or older), which isn't a problem in itself, but they don't seem to be able to join a SSID which is hidden.

I setup a hidden iot 2.4 ghz network that isn't broadcasted, and I have to make it visible/broadcasted in order for the bulbs to connect (even manually typing the credentials into the box). I waited 5 minutes and the bulb never connected, but as soon as I made the network visible, it was able to connect.

Once the bulbs are connected, then I am able to hide the network again and they seem to connect just fine after the initial connection has been made. FWIW, I'm using Unifi APs

**Comment by KaufHA** [comment]
Thanks for the feedback.  We didn't realize early on that ESPHome wouldn't connect to hidden networks without the [fast_connect](https://esphome.io/components/wifi.html?highlight=fast_connect#configuration-variables) option enabled in wifi settings, so older versions don't have it and we enabled it in an update.  Sorry for the inconvenience.  Glad it sounds like you got it figured out.  I added a note to the [troubleshooting page](https://github.com/KaufHA/common/blob/main/README.md) that may help others.
