### ISSUE TITLE
Unable to update any lights

### ISSUE THREAD

**Issue by GinAndBacon** [KaufHA/kauf-rgbww-bulbs#24]
First time I have ever had an issue but during the latest update I get

Failed config

select: [source /config/esphome/.esphome/packages/0cf47246/kauf-bulb.yaml:223]
  
  Component select cannot be loaded via YAML (no CONFIG_SCHEMA).

and then

number: [source /config/esphome/.esphome/packages/0cf47246/kauf-bulb.yaml:301]
  
  Component number cannot be loaded via YAML (no CONFIG_SCHEMA).

Attached are the full logs. Each work with zero issues through HA or going directly to the IP. I also have the Kauf power switch and get the same error but with a different line number and only one line number instead of two. Really don't feel like reinstalling all four lights. Did not create an issue for the power switch yet as it looks like both of the files that it references (kauf-bulb.yaml) was updated 18 hours ago. Also attached is the config for one of the four lights. All have the same config besides name/friendly name and IP. I also have four lights from another vendor and they all updated with zero issues today.

[kauf_light_error_log.txt](https://github.com/KaufHA/kauf-rgbww-bulbs/files/10032139/kauf_light_error_log.txt)
[color-light-four.txt](https://github.com/KaufHA/kauf-rgbww-bulbs/files/10032245/color-light-four.txt)

**Comment by bkaufx** [comment]
Try cleaning build files.  If that doesn't work, delete the .esphome/packages and .esphome/external_components subdirectories within the ESPHome config directory.

I removed the custom number and select components since they weren't needed.  For some reason you are stuck looking for those components in the custom folder and not using the stock components.  I think the above steps will fix it.  Let me know if not.

**Comment by GinAndBacon** [comment]
Cleaning the build files resulted in the same error but deleting the .esphome/packages and .esphome/external_components subdirectories fixed the issue and I just updated on light with zero issues. You can close (unless I have to close) this issue. Many thanks to your quick and timely response and way to resolve.

**Comment by KaufHA** [comment]
I figured out a workaround for this so shouldn't be a problem for anyone else.  Basically, always referring to a tagged version of the common github repo so that the ESPHome dashboard will place the updated repo into a new folder without empty subfolders.
