### ISSUE TITLE
Anyone else having issues with longevity?

### ISSUE THREAD

**Issue by applehomekit1** [KaufHA/kauf-rgbww-bulbs#31]
I have only had these bulbs since June of last year, and I have another one that started flickering, unscrewed and reinserted in socket only for it to stop working completely. It was on the most recent update. Not sure if I want to invest another 15 bucks in a bulb that doesn't last.

**Comment by bkaufx** [comment]
A few people have had issues. I've sent everyone that has reached out another bulb.  I think the replacements have mostly been successful.  I can only think of one person that got a replacement and then the replacement went out.  In the latest hardware revision I increased the specs on the power supply output cap that seems to be the specific part going out.  Hopefully that will help.

If you email me your address I'll get you replacements.  brian@kaufha.com

**Comment by applehomekit1** [comment]
You had sent me replacements for a few others a couple months ago that had similar issue.I appreciate the offer of replacement.

Matt Arnold
163 Timber Ridge Rd.
Jonesborough, TN 37659

**Comment by bitmux** [comment]
@bkaufx you were so sporting to send me a replacement bulb, I have a second (original) bulb going down and I'm not afraid to crack it open.. I'm totally comfortable going after the bad cap and replacing it, trouble is I haven't figured out how to get into the power supply section of the bulb is it a destructive process?

**Comment by gingerbreadassassin** [comment]
@bkaufx I have quite a few (10+) of these that I purchased Nov '21 - Jan '22 that have failed in a manner that has me thinking failed capacitors. They won't power on, but do flicker when screwed in. When unscrewing them, the flicker continues, though decreases in frequency and intensity. Like @bitmux, I'd love to try to fix these myself if there's a non-destructive way to get to the power supply.

**Comment by bkaufx** [comment]
Yea send me an email and I can send out replacements.  brian@kaufha.com.

I don't know that it's easy to get to the power supply.  On the original run the LED heat spreader popped out of the housing pretty easy but I think lately they've been crimping them a little tighter.  I think the BLF15 ones are going to be very tough.  The main issue there is the adhesive that keeps the PCB in the housing.  Maybe something could eat that away easily but I haven't had time to figure it out.
