### ISSUE TITLE
No brightness control in WLED or xLights via DDP

### ISSUE THREAD

**Issue by Kebo2r** [KaufHA/kauf-rgbww-bulbs#62]
I have normal dimming control on the bulb web GUI but brightness/dimming doesn't seem to function when controlling via DDP through WLED or xLights.  The bulbs flicker and dim one step before off but that's it.  Any ideas?  Thanks!

**Comment by Kebo2r** [comment]
Nevermind.  Just figured out WLED and The Kauf integration were fighting each other

**Comment by veteze** [comment]
> Nevermind. Just figured out WLED and The Kauf integration were fighting each other

What was the fix in WLED in the end for future generations who happen along your path? ;)
